spring:
  application:
    name: accounts-app
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  cloud:
    consul:
      host: localhost          # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)
      discovery:
        service-name: accounts-app
#      config:
#        enabled: true            # Включаем Consul Config для внешней конфигурации
#        defaultContext: application  # Контекст по умолчанию
#        prefixes: config

server:
  port: ${SERVER_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always