spring:
  application:
    name: frontui-app
  datasource:
    url: ${SPRING_DATASOURCE_URL_FRONTUI:jdbc:postgresql://localhost:5433/frontuidb}
    username: ${SPRING_DATASOURCE_USERNAME_FRONTUI:user}
    password: ${SPRING_DATASOURCE_PASSWORD_FRONTUI:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8080/realms/master}
        registration:
          front-ui:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: front-ui
            client-secret: ${FRONTUI_OAUTH2_SECRET:sZ3qUAEtCv3YzE6b9n3FZCrnJ5VGDsXo}
            scope: profile
            clientAuthenticationMethod: client_secret_post

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}          # Адрес Consul (по умолчанию localhost)
      port: ${CONSUL_PORT:8500}               # Порт Consul (8500 по умолчанию)
      discovery:
        service-name: frontui-app
#      config:
#        enabled: true            # Включаем Consul Config для внешней конфигурации
#        prefixes: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
#        defaultContext: application  # Контекст по умолчанию

server:
  port: ${FRONTUI_SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1 # частота трейсов

application:
  secret:
    key: ${FRONTUI_SECRET_REMEMBERME_KEY:secretkey}

accountsapp:
  url: ${ACCOUNTS_SERVICE_URL:http://accounts-app}
cashapp:
  url: ${CASH_SERVICE_URL:http://cash-app}