pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = credentials('DOCKER_REGISTRY')
        GITHUB_USERNAME = credentials('GITHUB_USERNAME')
        DB_PASSWORD     = credentials('DB_PASSWORD')
        DB_ACCOUNT_NAME         = 'accountdb'
        DB_ACCOUNT_USER         = 'user'

        DB_FRONTUI_NAME         = 'frontuidb'
        DB_FRONTUI_USER         = 'user'
        IMAGE_TAG       = "${env.BUILD_NUMBER}"
    }

    stages {
//         stage('Build & Unit Tests') {
//             stage('Commonms Service') {
//                 docker build -t ${DOCKER_REGISTRY}/commons:${IMAGE_TAG} commons
//             }
//
//             parallel {
//                 stage('Accounts-app Service') {
//                     steps {
//                         dir('accounts-app') {
//                             sh 'mvn clean test'
//                         }
//                     }
//                 }
//                 stage('Cash-app Service') {
//                     steps {
//                         dir('cash-app') {
//                             sh 'mvn clean test'
//                         }
//                     }
//                 }
//                 stage('Frontui-app Service') {
//                     steps {
//                         dir('frontui-app') {
//                             sh 'mvn clean test'
//                         }
//                     }
//                 }
//             }
//         }

        stage('Install Helm') {
                    steps {
                        script {
                            sh 'curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash'
                        }
                    }
                }

        stage('Deploy Prometheus') {
                    steps {
                        script {
                            sh 'helm repo add prometheus-community https://prometheus-community.github.io/helm-charts'
                            sh 'helm repo update'
                            sh 'helm install prometheus prometheus-community/prometheus -f helm_my_app/charts/prometheus/values.yaml'
                        }
                    }
                }

        stage('Deploy Grafana') {
                    steps {
                        script {
                            sh 'helm repo add grafana https://grafana.github.io/helm-charts'
                            sh 'helm repo update'
                            sh 'helm install grafana grafana/grafana -f helm_my_app/charts/grafana/values.yaml'
//                             sh 'kubectl port-forward svc/grafana 3000:3000'
                        }
                    }
                }

        stage('Build Docker Images') {
            steps {
                   sh """
                   docker build -t ${DOCKER_REGISTRY}/accounts-app:${IMAGE_TAG} accounts-app
                   docker build -t ${DOCKER_REGISTRY}/cash-app:${IMAGE_TAG} cash-app
                   docker build -t ${DOCKER_REGISTRY}/frontui-app:${IMAGE_TAG} frontui-app
                   """
            }
        }

        stage('Push Docker Images') {
            steps {
                withCredentials([string(credentialsId: 'GHCR_TOKEN', variable: 'GHCR_TOKEN')]) {
                    sh """
                    echo \$GHCR_TOKEN | docker login ghcr.io -u ${GITHUB_USERNAME} --password-stdin
                    docker push ${DOCKER_REGISTRY}/accounts-app:${IMAGE_TAG}
                    docker push ${DOCKER_REGISTRY}/cash-app:${IMAGE_TAG}
                    docker push ${DOCKER_REGISTRY}/frontui-app:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Install PostgreSQL to TEST') {
            steps {
                sh """
                helm repo add bitnami https://charts.bitnami.com/bitnami
                helm repo update

                helm upgrade --install postgres bitnami/postgresql \\
                  --namespace test --create-namespace \\
                  --set auth.database=${DB_ACCOUNT_NAME} \\
                  --set auth.username=${DB_ACCOUNT_USER} \\
                  --set auth.password=${DB_PASSWORD}
                """
            }
        }

        stage('Create DB Secrets for TEST') {
            steps {
                sh """
                kubectl create secret generic account-service-db \\
                  --from-literal=password=${DB_PASSWORD} \\
                  -n test --dry-run=client -o yaml | kubectl apply -f -

                kubectl create secret generic frontui-service-db \\
                  --from-literal=password=${DB_PASSWORD} \\
                  -n test --dry-run=client -o yaml | kubectl apply -f -
                """
            }
        }


        stage('Helm Deploy to TEST') {
            steps {
                sh """
                helm upgrade --install accounts-app-service helm_my_app/charts/accounts-app \\
                  --namespace test --create-namespace \\
                  --set image.repository=${DOCKER_REGISTRY}/accounts-app-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=customer.test.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                helm upgrade --install cash-app-service helm_my_app/charts/cash-app \\
                  --namespace test --create-namespace \\
                  --set image.repository=${DOCKER_REGISTRY}/cash-app-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=order.test.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                  helm upgrade --install frontui-app-service helm_my_app/charts/frontui-app \\
                                    --namespace test --create-namespace \\
                                    --set image.repository=${DOCKER_REGISTRY}/frontui-app-service \\
                                    --set image.tag=${IMAGE_TAG} \\
                                    --set ingress.enabled=true \\
                                    --set ingress.hosts[0].host=order.test.local \\
                                    --set ingress.hosts[0].paths[0].path="/" \\
                                    --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"
                """
            }
        }

        stage('Manual Approval for PROD') {
            steps {
                input message: 'Deploy to PROD environment?', ok: 'Yes, deploy'
            }
        }

        stage('Install PostgreSQL to PROD') {
            steps {
                sh """
                helm upgrade --install postgres bitnami/postgresql \\
                  --namespace prod --create-namespace \\
                  --set auth.database=${DB_ACCOUNT_NAME} \\
                  --set auth.username=${DB_ACCOUNT_USER} \\
                  --set auth.password=${DB_PASSWORD}
                """
            }
        }

        stage('Create DB Secrets for PROD') {
            steps {
                sh """
                kubectl create secret generic account-service-db \\
                  --from-literal=password=${DB_PASSWORD} \\
                  -n prod --dry-run=client -o yaml | kubectl apply -f -

                kubectl create secret generic frontui-service-db \\
                  --from-literal=password=${DB_PASSWORD} \\
                  -n prod --dry-run=client -o yaml | kubectl apply -f -
                """
            }
        }

        stage('Install Kafka to PROD') {
            steps {
                sh """
                helm repo add bitnami https://charts.bitnami.com/bitnami

                helm repo update

                helm upgrade install my-kafka bitnami/kafka --set replicaCount=1 --set persistence.enabled=true
                """
            }
        }

        stage('Install Zipkin to PROD') {
                    steps {
                        sh """
                        helm upgrade --install my-zipkin helm_my_app/charts/zipkin
                        """
                    }
                }

        stage('Helm Deploy to PROD') {
            steps {
                sh """
                helm upgrade --install accounts-app-service helm_my_app/charts/accounts-app \\
                  --namespace prod --create-namespace \\
                  --set image.repository=${DOCKER_REGISTRY}/accounts-app-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=customer.prod.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                helm upgrade --install cash-app-service helm_my_app/charts/cash-app \\
                  --namespace prod --create-namespace \\
                  --set image.repository=${DOCKER_REGISTRY}/cash-app-service \\
                  --set image.tag=${IMAGE_TAG} \\
                  --set ingress.enabled=true \\
                  --set ingress.hosts[0].host=order.prod.local \\
                  --set ingress.hosts[0].paths[0].path="/" \\
                  --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                  helm upgrade --install frontui-app-service helm_my_app/charts/frontui-app \\
                                    --namespace prod --create-namespace \\
                                    --set image.repository=${DOCKER_REGISTRY}/frontui-app-service \\
                                    --set image.tag=${IMAGE_TAG} \\
                                    --set ingress.enabled=true \\
                                    --set ingress.hosts[0].host=order.prod.local \\
                                    --set ingress.hosts[0].paths[0].path="/" \\
                                    --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"

                  helm upgrade --install notifications-app-service helm_my_app/charts/notifications-app \\
                                    --namespace prod --create-namespace \\
                                    --set image.repository=${DOCKER_REGISTRY}/notifications-app-service \\
                                    --set image.tag=${IMAGE_TAG} \\
                                    --set ingress.enabled=true \\
                                    --set ingress.hosts[0].host=order.prod.local \\
                                    --set ingress.hosts[0].paths[0].path="/" \\
                                    --set ingress.hosts[0].paths[0].pathType="ImplementationSpecific"
                """
            }
        }
    }
}